version: "3.5"

networks:
  proxy:
    name: example
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24

volumes:
  postgres_data:


services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres_3800
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
